[platformio]
# Dòng này quyết định xem mặc định khi nhấn nút Build/Upload thì con chip nào sẽ chạy
default_envs = CH32V003J4M6

# Cấu hình chung cho cả 3 con chip để tránh lặp lại code (DRY)
[env]
platform = ch32v
framework = ch32v003fun
upload_protocol = minichlink
debug_tool = minichlink

# 1. Cấu hình cho bản 8 chân
[env:CH32V003J4M6]
board = genericCH32V003J4M6
build_flags = -DCH32V003_J4M6

# 2. Cấu hình cho bản 16 chân
[env:CH32V003A4M6]
board = genericCH32V003A4M6
build_flags = -DCH32V003_A4M6

# 3. Cấu hình cho bản 20 chân
[env:CH32V003F4P6]
board = genericCH32V003F4P6
build_flags = -DCH32V003_F4P6